package com.example.instagramproject.util.pic_purify;

public enum PicPurifyModerationTaskName {
    PORN_MODERATION,
    SUGGESTIVE_NUDITY_MODERATION,
    GORE_MODERATION,
    MONEY_MODERATION,
    WEAPON_MODERATION,
    DRUG_MODERATION,
    HATE_SIGN_MODERATION,
    OBSCENE_GESTURE_MODERATION,
    QR_CODE_MODERATION
}
